cirro:
  site: "https://api.staging.cirro.io"
  authorize_url: "https://staging.cirro.io/oauth/authorize"
  app_id: "cirro-example-app-id-development"
  app_secret: "cirro-example-app-secret-development"
  api_version: "v1"
host: https://example.cirro.io
